version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 3
    reviewers:
      - 'ConcaveFi/frontend'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependabot'
      - 'dependencies'
    target-branch: 'develop'
