name: Test Package

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
      NEXT_PUBLIC_CONCAVE_RPC_KEY: ${{ secrets.NEXT_PUBLIC_CONCAVE_RPC_KEY }}
      NEXT_PUBLIC_INFURA_ID: ${{ secrets.NEXT_PUBLIC_INFURA_ID }}
      NEXT_PUBLIC_MORALIS_TOKEN: ${{ secrets.NEXT_PUBLIC_MORALIS_TOKEN }}
      NEXT_PUBLIC_UNIVERSAL_GA: ${{ secrets.NEXT_PUBLIC_UNIVERSAL_GA }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Test
        run: yarn && yarn test
